### PR TITLE
Fix mpf numbers II

### PR DESCRIPTION
**Pull request by arthurkehrwald**
Fixed version of the borked #22 PR

### CODE REVIEW

**Comment by freezy** [comment]
I've rebased this and pushed. However I'm getting compilation errors. Any idea?

image

**Comment by arthurkehrwald** [comment]
This is because you merged #27 before this

**Comment by freezy** [comment]
Can you push a fix? Then I'll merge.

**Comment by arthurkehrwald** [comment]
Done

**Comment by freezy** [comment]
Thanks!

**Pull request merged**
